### ISSUE TITLE
SolverBenchmark release

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/SolverBenchmark.jl#11]

**Comment by dpo** [comment]
It's starting to look good.

**Comment by abelsiqueira** [comment]
I couldn't think if anything else to add, so I think it's time for a release. Attobot is on?

**Comment by dpo** [comment]
It is 🔛 !

**Comment by abelsiqueira** [comment]
We have some `PkgBenchmark`-related error on the tags build: https://travis-ci.org/JuliaSmoothOptimizers/SolverBenchmark.jl/jobs/500643625#L1027

**Comment by abelsiqueira** [comment]
Error: when travis downloads a tag build, there is no `master`.
Looking into fix now.

**Comment by dpo** [comment]
`git rev-list --parents -n 1 $(git rev-parse HEAD) | awk '{print $2}'` will give you the previous commit hash. Could we use that instead of `master`?

**Comment by abelsiqueira** [comment]
I fixed by fetching master.

**Comment by dpo** [comment]
Congrats on the first release! Thank you!
