### ISSUE TITLE
GenericExecutionStats has no field counters when using solve_problems

### ISSUE THREAD

**Issue by geoffroyleconte** [JuliaSmoothOptimizers/SolverBenchmark.jl#123]
Since the counters have been removed from the `GenericExecutionStats` type I have this error message when using `solve_problems`
```julia
┌ Error: caught exception
│   e = type GenericExecutionStats has no field counters
```
This does not seem to be shown in the breakage tests so I open an issue just in case.

**Comment by tmigot** [comment]
I got something similar
```
┌ Warning: failed to run `@example` block in src/benchmark.md:124-126
│ ```@example ex1
│ print_pp_column(:neval_jac, stats) # with respect to number of jacobian evaluations
│ ```
│   c.value = ArgumentError: reducing over an empty collection is not allowed
```
when `stats` is the result of `bmark_solvers` in DCISolver.jl https://github.com/JuliaSmoothOptimizers/DCISolver.jl/runs/7733825128?check_suite_focus=true
