### ISSUE TITLE
Solver name displayed after Info: ?

### ISSUE THREAD

**Issue by DoctorDro** [JuliaSmoothOptimizers/SolverBenchmark.jl#150]
Dear all,

is there any possibility to enable the printing of the solver being tested after the ```Info:``` ? Because if you are testing several of them and something is wrong or you see some exception, you do not know which solver concerns. 

```Info:``` as a string is useless by the way, since it is obvious that what is printed is information. Possibly ```Info:``` should be replaced by the name of the solver being tested ```Newton:``` or ```LBFGS:```?

Any ideas?

**Comment by tmigot** [comment]
Hi! That's a good suggestion.

If I keep the same example as in #149
```
using NLPModelsTest
using DataFrames, SolverCore, SolverBenchmark

function newton(nlp)
stats = GenericExecutionStats(nlp)
set_solver_specific!(stats, Symbol("isConvex"), :is_convex)
return stats
end
lbfgs(nlp) = newton(nlp)

solvers = Dict(
    :Newton => newton,
    :LBFGS => lbfgs
)
problems = [NLPModelsTest.BROWNDEN()]
stats = bmark_solvers(solvers, problems)
```

Modifying this line https://github.com/JuliaSmoothOptimizers/SolverBenchmark.jl/blob/24571ffbb92abd11652a62c9c10aadb2df40f166/src/bmark_solvers.jl#L21 for `@info "Running solver $(name) with function $(solver)"` for instance would return
```
julia> stats = bmark_solvers(solvers, problems)
[ Info: Running solver LBFGS with function lbfgs
[ Info:            Name    nvar    ncon           status      Time      f(x)      Dual    Primal
[ Info: BROWNDEN_manual       4       0          unknown       Inf       Inf       Inf   0.0e+00
[ Info: Running solver Newton with function newton
[ Info:            Name    nvar    ncon           status      Time      f(x)      Dual    Primal
[ Info: BROWNDEN_manual       4       0          unknown       Inf       Inf       Inf   0.0e+00
```

Would that solve your issue?

**Comment by tmigot** [comment]
I like your suggestion. Do you want to open a PR for this?

**Comment by tmigot** [comment]
This is an issue. a Pull Request would be an actual change to the code :)

**Comment by tmigot** [comment]
No problem, feel free to let me know if that sounds too much work.
A pull request is a proposal to merge a set of changes from one branch into another.

As you may have noticed the code of this package is available here https://github.com/JuliaSmoothOptimizers/SolverBenchmark.jl , and to modify it, you need to open a pull request that will then be reviewed and validated before added to the code.

I think the Github procedure is described here https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjYyObentOEAxVhGVkFHSnAAWcQFnoECCYQAQ&url=https%3A%2F%2Fdocs.github.com%2Farticles%2Fcreating-a-pull-request&usg=AOvVaw0OafNHvMFfUq56q9rPOrPT&opi=89978449 . If you decide to go for it, I can pinpoint the places where the code needs to be changed.

**Comment by tmigot** [comment]
The line to be changed for the header:
https://github.com/JuliaSmoothOptimizers/SolverBenchmark.jl/blob/bbec05989ff2a1e06e7e5d9f0db0d3aebe6b9310/src/bmark_solvers.jl#L21
The line that prints after each problem:
https://github.com/JuliaSmoothOptimizers/SolverBenchmark.jl/blob/bbec05989ff2a1e06e7e5d9f0db0d3aebe6b9310/src/run_solver.jl#L127

I am too fond of the iteration count, because the definition of an iteration highly depend from one solver to another. It still is an information you can get from the result of the `bmark_solvers`.

**Comment by dpo** [comment]
Why isn’t it sufficient to enable debug logging with the code as it is to see the solver and problem name? Something like
```julia
using Logging

logger = ConsoleLogger(stdout, Debug)
stats = with_logger(logger)
  bmark_solvers(solvers, problems)
end
```

**Comment by tmigot** [comment]
If we use the debug mode it gives:
```
julia> stats = with_logger(logger) do                                                                         
       bmark_solvers(solvers, problems)                                                                       
       end
┌ Debug: running
│   name = :LBFGS
│   solver = lbfgs (generic function with 1 method)
└ @ SolverBenchmark C:\Users\tangi\.julia\dev\SolverBenchmark.jl\src\bmark_solvers.jl:21
[ Info:            Name    nvar    ncon           status      Time      f(x)      Dual    Primal
[ Info: BROWNDEN_manual       4       0          unknown       Inf       Inf       Inf   0.0e+00
┌ Debug: running
│   name = :Newton
│   solver = newton (generic function with 1 method)
└ @ SolverBenchmark C:\Users\tangi\.julia\dev\SolverBenchmark.jl\src\bmark_solvers.jl:21
[ Info:            Name    nvar    ncon           status      Time      f(x)      Dual    Primal
[ Info: BROWNDEN_manual       4       0          unknown       Inf       Inf       Inf   0.0e+00
```
which is also good. In a sense that it is slightly weird to have the `@info` printed without the `@debug` header. I think either we use `@debug` for all or `@info`.

Then, I understand @DoctorDro idea to have the name of the solver printed somewhere in case you solve a ton of problems.

**Comment by tmigot** [comment]
Hey @DoctorDro ! Sorry, I know it is not trivial. @dpo opened a PR to at least add the name of the solver in the info section. I let the other part in a new issue #154 for someone to grab.

Regarding Github, the process is more as follows:
-> create a fork of the repository you plan to contribute to.
-> make a new branch in this fork.
-> add your new code (and test that it works)
-> open a Pull Request from this branch of your fork to the main repository.
I hope it clarifies it.
