### ISSUE TITLE
Add a column `solver name` in the logs of `bmark_solvers`

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/SolverBenchmark.jl#154]
This was initiated in #150 and discussed in #153 .

The line that prints after each problem:
https://github.com/JuliaSmoothOptimizers/SolverBenchmark.jl/blob/bbec05989ff2a1e06e7e5d9f0db0d3aebe6b9310/src/run_solver.jl#L127

MWE
```
using NLPModelsTest
using DataFrames, SolverCore, SolverBenchmark

function newton(nlp)
stats = GenericExecutionStats(nlp)
set_solver_specific!(stats, Symbol("isConvex"), :is_convex)
return stats
end
lbfgs(nlp) = newton(nlp)

solvers = Dict(
    :Newton => newton,
    :LBFGS => lbfgs
)
problems = [NLPModelsTest.BROWNDEN()]
stats = bmark_solvers(solvers, problems)
```

**Comment by Jay-sanjay** [comment]
HI @tmigot  I was trying to tackle this issue and trying something like this 
```
          info_hdr_override = merge(info_hdr_override, Dict(:solver => s.solver_name))
          @info log_header(colstats, types[col_idx], hdr_override = info_hdr_override)

```

Is it the way, or what other things I need to handle ?

**Comment by tmigot** [comment]
Hi @Jay-sanjay ! Thanks for the suggestion, actualy, there is an ongoing PR to fix this but the link wasn't done.
