### ISSUE TITLE
Bmark_solvers bugs on solvers that have solver_specific stats

### ISSUE THREAD

**Issue by MaxenceGollier** [JuliaSmoothOptimizers/SolverBenchmark.jl#170]
When we use `bmark_solvers`, if the first problem encounters an exception thrown by the solver and if the solver has some `solver_specific` stats, then all the following problems will encounter a `DimensionMismatch` exception.

The following code benchmarks two instances of the `dummy_solver` on two problems. On the first problem, it throws an exception.
The first instance has the default parameter, it solves the second problem.
The second instance sets a `solver_specific` `:foo` at each iteration, the benchmark fails.

```
using Logging
using NLPModels, ADNLPModels
using SolverCore
using SolverBenchmark

import SolverCore.dummy_solver


problems = [
  ADNLPModel(x -> sum(x .^ 2), ones(2), name = "Quadratic"),
  ADNLPModel(
    x -> (x[1] - 1)^2 + 4 * (x[2] - x[1]^2)^2,
    ones(2),
    x -> [x[1]^2 + x[2]^2 - 1],
    [0.0],
    [0.0],
    name = "Cons Rosen",
  ),
]

solvers = Dict(
  :dummy => dummy_solver,
  
  :dummy_solver_specific => 
    nlp -> dummy_solver(
      nlp,
      callback = (nlp, solver, stats) -> begin
        set_solver_specific!(stats, :foo, 1)
      end
    ),
)
stats = bmark_solvers(solvers, problems)
```
This produces 
```
[ Info: running solver dummy
┌ Error: caught exception
│   e = solver assumes Hessian is dense
└ @ SolverBenchmark C:\Users\mgoll\SolverBenchmark.jl\src\run_solver.jl:163
[ Info:           dummy        Quadratic       2       0        exception       0       Inf       Inf       Inf       Inf
[ Info:          Solver             Name    nvar    ncon           status    iter      Time      f(x)      Dual    Primal  
[ Info:           dummy       Cons Rosen       2       1      first_order       4   2.8e+00   4.4e-02   3.6e-10   1.6e-11
[ Info: running solver dummy_solver_specific
┌ Error: caught exception
│   e = solver assumes Hessian is dense
└ @ SolverBenchmark C:\Users\mgoll\SolverBenchmark.jl\src\run_solver.jl:163
[ Info: dummy_solver_specific        Quadratic       2       0        exception       0       Inf       Inf       Inf       Inf
┌ Error: caught exception
│   e = DimensionMismatch: length of new column foo which is 0 must match the number of rows in data frame (1)
└ @ SolverBenchmark C:\Users\mgoll\SolverBenchmark.jl\src\run_solver.jl:163
[ Info: dummy_solver_specific       Cons Rosen       2       1        exception       0       Inf       Inf       Inf       Inf
```
I guess this is due to the fact that the data frame is not well initialized when an exception is initially thrown.

**Comment by tmigot** [comment]
Thanks @MaxenceGollier for the issue. This is indeed a bug. The main issue here is that the DataFrame build for each solver contains columns with solver specifics that we detect from the returned stats (`stats.solver_specific`). So, if the first run fails, we start populating the DataFrame without knowing it.

https://github.com/JuliaSmoothOptimizers/SolverBenchmark.jl/blob/360eb42a04beca2a57ee6e894481ebe60695a6b0/src/run_solver.jl#L126

From the code, we might have a similar issue if we `skipthis` the first instance.

**Comment by MaxenceGollier** [comment]
I added a PR #171
