### ISSUE TITLE
Different colors for the same method  --- benchmarks

### ISSUE THREAD

**Issue by amontoison** [JuliaSmoothOptimizers/SolverBenchmark.jl#36]
I ran some benchmarks and I remarked that colors between the main benchmark (with all methods) and the other ones (1 vs 1) are different. Did you update something or the problem comes from Plots.jl?
https://gist.github.com/amontoison/034ce9a5cae9f4e65346bd56d589c867

**Comment by dpo** [comment]
Are you using the PyPlot backend? What if you use GR?

**Comment by amontoison** [comment]
Yes, I was using PyPlot backend. I also tested GR backend and I had the same problem.
https://gist.github.com/amontoison/b2454eb82b9fcb76d1cb2b92a3d2610c
But I think I found the problem the problem. In `profiles.jl`, colors are only defined for combinations of solvers 2 by 2. We need to define them before profiles with all solvers.
